### ISSUE TITLE
مشکل نمایش فید در سینما و عکاسی

### ISSUE THREAD

**Issue by developer1980** [ashkanRmk/awesome-persian-podcasts#105]
مشکل نمایش فید پادکست ها در سینما و عکاسی
و  اضافه کردن پادکست جدید در سینما و عکاسی با مشکلاتی مواجه هست

**Comment by ashkanRmk** [comment]
ممنون از فیدبکت
ببین اگر امکانش هست اصلاحات رو توقالب PR بفرستی 
خیلی بهتره
بازم ممنون
