### ISSUE TITLE
اضافه کردن دسته‌ی فلسفه

### ISSUE THREAD

**Issue by houmannourian** [ashkanRmk/awesome-persian-podcasts#106]
پادکست های [انسانک](https://castbox.fm/channel/%D9%BE%D8%A7%D8%AF%DA%A9%D8%B3%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A7%D9%86%D8%B3%D8%A7%D9%86%DA%A9-%7C-Ensanak-id2666783?nojump=1&country=us) و [می](https://castbox.fm/channel/%D9%BE%D8%A7%D8%AF%DA%A9%D8%B3%D8%AA-%D9%85%DB%8C-%D9%80-%D8%AE%D9%88%D8%A7%D9%86%D8%B4-%D8%AD%DA%A9%D9%85%D8%AA-%D8%B2%D9%86%D8%AF%DA%AF%DB%8C-%D8%B4%D9%88%D9%BE%D9%86%D9%87%D8%A7%D9%88%D8%B1-%7C-Mey-id3944100?nojump=1) بسیار جذاب بوده و قابل اضافه کردن به دسته بندی فلسفه هستند.

**Comment by ashkanRmk** [comment]
ممنون از پیشنهادت
