### ISSUE TITLE
اضافه کردن تاریخ و عنوان آخرین پست

### ISSUE THREAD

**Issue by Marjani** [ashkanRmk/awesome-persian-podcasts#11]
سلام
به نظرم بد نباشه، توی جدول های تاریخ و عنوان آخرین پست رو هم اضافه کنیم، که بشه با یه نگاه دید کدوم ها تازه به روز شدند، و آخرین پادکست در مورد چی بوده.
بعضی ها رو بررسی کردم بیش از 2 ساله که متوقف شده

**Comment by Ashkan-rmk** [comment]
@Marjani سلام
ممنون از نظرتون، اما ما یبشتر قصد داریم این ریپو آرشیوی از بهترین پادکست‌های فارسی‌زبان باشه..
بروز بودن مطالب زیاد اهمیتی نداره گرچه بودنش هم خالی از لطف نیست. اما مثلن پادکست رادیو چهرازی به عنوان یکی از معروف‌ها خیلی مدت هستش که دیگه تولید نمیشه و ما صرفن قصدمون معرفی پادکست‌ها توی موضوعات مختلف هست.
باز هم اگر میتونین این بخش از کار رو توسعه بدین خوشحال میشیم :) در واقع هدف نهایی هم همین هستش که بازدید کننده‌ها نظرات خودشون رو روی این ریپو اعمال کنن...
ممنون ازتون :)

**Comment by SamaneYaghoobi** [comment]
@Marjani @Ashkan-rmk 
پیشنهاد خیلی خوبیه ولی ما الان پادکست ها رو دستی وارد میکنیم، واسه پادکست هایی که همواره بروز میشن و قسمت جدید منتشر میکنن، اضافه کردن تاریخ آخرین قسمتشون کمی مشکله.
اگر کسی وقت داشته باشه و روی توسعه این بخش کارکنه خیلی استقبال می‌کنیم :)

**Comment by farshadasadpour** [comment]
اضافه کردن آخرین تاریخ پشت به نظرم یکم سخته !! 
من دارم سعی میکنمکل پادکست ها رو به ترتیب الفبا مرتب کنم
