### ISSUE TITLE
Add Castbox link

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [ashkanRmk/awesome-persian-podcasts#28]
پینشهاد می کنم لینک کست باکس پادکست ها رو هم اضافه کنین

**Comment by Ashkan-rmk** [comment]
تمام پادکست‌های این لیست داخل کست‌باکس نیستن و از طرفی همه هم از کست‌باکس استفاده نمیکنن.


همینطور پیدا کردن لینک فیدیا لینک کست‌باکس یک مقدار مشکل هستش.
اگر شما و یا کسی دیگه‌ای تو این زمینه به ما کمک بکنه خوشحال میشم.

بازم ممنون از پیشنهادت

**Comment by SamaneYaghoobi** [comment]
@MahdiMajidzadeh ستون فید به لیست اضافه شد. ممنون ازتون
