### ISSUE TITLE
Add Sokoote Barreha Podcast

### ISSUE THREAD

**Issue by farhadfard** [ashkanRmk/awesome-persian-podcasts#41]
Please add bellow podcast under گفتگو محور

سکوت بره‌ها
[https://appurl.io/KEp3mHoPM](url)
ما به بحث پیرامون یک موضوع از مسائل هنری، فرهنگی یا اجتماعی می‌پردازیم

**Comment by SamaneYaghoobi** [comment]
@farhadfard ممنون از شما اضافه شد.
