### ISSUE TITLE
اصلاحیه

### ISSUE THREAD

**Issue by mehrdad2000** [ashkanRmk/awesome-persian-podcasts#46]
‏سلام 
 رادیو شمرون  ،  جا افتاده :)

ممنون

**Comment by farshadasadpour** [comment]
سلام 
لینک رادیو رو برامون اینجا بزار حتما اضافه میکنیم

**Comment by SamaneYaghoobi** [comment]
@mehrdad2000  مرسی از پیشنهادتت اضافه شد :)

**Comment by SamaneYaghoobi** [comment]
@mehrdad2000  مرسی از پیشنهادتت اضافه شد :)
