### ISSUE TITLE
مشکل لینک

### ISSUE THREAD

**Issue by xmha97** [ashkanRmk/awesome-persian-podcasts#84]
سلام این لینکی که بالای این ریپوزیتوری دادید کار نمی‌کنه:
http://podcasts.ashkaan.ir/
لطفا تا زمان درست شدن این مشکل، این لینک رو قرار بدید:
https://ashkanrmk.github.io/awesome-persian-podcasts/

**Comment by SamaneYaghoobi** [comment]
سلام ممنون که اطلاع دادی :)
اصلاح شد.
