### ISSUE TITLE
نمایش لینک و توضیحات پادکست هری پاتر

### ISSUE THREAD

**Issue by a-nahvi** [ashkanRmk/awesome-persian-podcasts#85]
ممنون از اینکه پادکست هری پاتر رو اضافه کردین
فقط اینکه نام پادکست به همراه لینک درست نمایش داده نمیشه
توضیحات پادکست:  با هر قسمت از این پادکست میخوایم شما رو توی دنیای هری پاتر غرق کنیم.
وب سایت هم ممنون میشم اضافه کنید: harrypotterpodcast.ir

**Comment by SamaneYaghoobi** [comment]
خیلی ممنونم که اطلاع دادین. اصلاح شد :)
